<?php

namespace Remg\UserBundle\Repository;

use Remg\UserBundle\Model\UserRepository as BaseRepository;

/**
 * EntityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
}
